all: lab2_1 lab2_2 lab2_3 lab2_4

lab2_1: 
	gcc -o lab2_1 lab2_1.c 

lab2_2: 
	gcc -o lab2_2 lab2_2.c 

lab2_3: 
	gcc -o lab2_3 lab2_3.c

lab2_4:
	gcc -o lab2_4 lab2_4.c

clean:
		rm lab2_1 lab2_2 lab2_3 lab2_4