all: ipc1 ipc1_alt ipc2 ipc3 ipc4 ipc5 

ipc1: 
	gcc -o ipc1 ipc1.c 

ipc1_alt: 
	gcc -o ipc1_alt ipc1_alt.c 

ipc2: 
	gcc -o ipc2 ipc2.c 

ipc3: 
	gcc -o ipc3 ipc3.c 

ipc4: 
	gcc -o ipc4 ipc4.c 

ipc5: 
	gcc -o ipc5 ipc5.c

clean:
	rm ipc1 ipc1_alt ipc2 ipc3 ipc4 ipc5 

